//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floracao
    {
        public int FloracaoID { get; set; }
        public int OrquideaID { get; set; }
        public Nullable<System.DateTime> FloracaoInicio { get; set; }
        public Nullable<System.DateTime> FloracaoTermino { get; set; }
        public Nullable<byte> Flores { get; set; }
        public Nullable<byte> Hastes { get; set; }
    
        public virtual Orquidea Orquidea { get; set; }
    }
}
