//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orquidea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orquidea()
        {
            this.Floracoes = new ObservableListSource<Floracao>();
            this.Repots = new ObservableListSource<Repot>();
            this.Mudas = new ObservableListSource<Orquidea>();
        }
    
        public int OrquideaID { get; set; }
        public int GeneroID { get; set; }
        public string Especie { get; set; }
        public int Numero { get; set; }
        public Nullable<int> Sequencial { get; set; }
        public string CorPrincipal { get; set; }
        public string CorSecundaria { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.DateTime> Termino { get; set; }
        public string Origem { get; set; }
        public Nullable<int> Matriz { get; set; }
        public string Observacoes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Floracao> Floracoes { get; set; }
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Repot> Repots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Orquidea> Mudas { get; set; }
        public virtual Orquidea OrquideaMatriz { get; set; }
    }
}
